#!/bin/bash

# Run test first
./script/test

build_dir="build"
entry_point="index.js"
target_point="d3-fusiontext"

# rollup -c $1  -f umd -n d3 -o $build_dir/$target_point.js -- $entry_point
rollup -c $1 -f umd -g d3-selection:d3,fusioncharts-smartlabel:d3 -n d3 -o $build_dir/$target_point.js -- $entry_point
uglifyjs $build_dir/$target_point.js -c negate_iife=false -m -o $build_dir/$target_point.min.js
